
language: node_js
node_js: '14.2.0'

cache:
  directories:
    - node_modules

before_script: cd api_node

script:
  - npm install
  - npm test

  # deploy:
  #   skip_cleanup: true

  #   provider: script
  #   script: ./deploy.sh

  #   on:
  #     branch: main
  #     node: '5'