
language: node_js
node_js: '12.2.0'

cache:
  directories:
    - node_modules

before_script: cd webInterfaces

script:
  - npm install
  - npm run serve

  # deploy:
  #   skip_cleanup: true

  #   provider: script
  #   script: ./deploy.sh

  #   on:
  #     branch: main
  #     node: '5'