version: '3.6'
services:
  webinterfaces:
    container_name: webInterfaces
    build: 
        context: ./webInterfaces/
        dockerfile: Dockerfile
    ports: 
        - 8080:8080
    restart: always
    

#   db:
#     restart: always
#     image: 'postgres:11-alpine'
#     container_name: 'postgres-db'
#     # env_file:
#     #   - .env
#     environment:
#     #   PGDATA: /var/lib/postgresql/data
#       POSTGRES_PASSWORD: postgres #${POSTGRES_PASSWORD}
#       POSTGRES_USER: postgres #${POSTGRES_USER}
#       POSTGRES_DB: theme01_dev #${POSTGRES_DB}
#       POSTGRES_HOST: localhost #${POSTGRES_HOST}
#     # volumes:
#     #   - 'pgdata:/var/lib/postgresql/data'
#     ports:
#       - 5432:5432
#     networks: 
#       - internal
#   api:
#     build:
#       context: ./api
#       dockerfile: Dockerfile
#     restart: always
#     container_name: theme01-api
#     depends_on:
#       - db
#     # environment:
#     #   MIX_ENV: dev
#     env_file:
#       - .env
#     ports:
#       - 4000:4000
#     networks: 
#       - internal
#     # volumes:
#     #   - .:/app
#     # volumes:
#     #     pgdata:
# networks: